## Exercise 4

#### Nomor 1

In [2]:
import numpy as np

In [5]:
x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#Jawaban
x[4] = 11

x

array([ 0,  1,  2,  3, 11,  5,  6,  7,  8,  9])

#### Nomor 2

In [22]:
y = np.array([[0,1,2],[3,4,5]])
y.shape

(2, 3)

In [23]:
#Jawaban
y_answer = y.reshape(3,2)
y_answer

array([[0, 1],
       [2, 3],
       [4, 5]])

In [24]:
y_answer.shape

(3, 2)

#### Nomor 3

In [86]:
z_zeros = np.zeros(16).reshape(4,4)
z_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
z_answer = z_zeros
z_answer

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
z_answer[0] = 1.0
z_answer[3] = 1.0
z_answer

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [100]:
z_answer[:,0] = 1
z_answer[:,3] = 1
z_answer

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### Nomor 4

In [67]:
a = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])

In [71]:
a[2,0]

array([1, 1, 2])

# Assignment 1

#### Nomor 2

In [77]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
a_answer = np.hsplit(a, (0,2))
a_answer

[array([], shape=(4, 0), dtype=int32),
 array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

#### Nomor 1

In [81]:
from numpy import random

In [84]:
b = random.randint(0, 3, size=(4,4))
b

array([[2, 2, 2, 1],
       [2, 1, 0, 2],
       [2, 2, 1, 0],
       [1, 2, 1, 0]])